name: demode
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.0.1
  image_picker: ^1.0.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  google_sign_in: ^6.1.6
  collection: ^1.18.0
  path: ^1.8.3
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  logging: ^1.2.0
  flutter_lints: ^3.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
